# 這是單純抽神包的設定檔示範

# TARGET_PACK: 抽甚麼包: charizard, mewtwo, pikachu, mew
TARGET_PACK: "mew"

# !!! 重要 !!!
# 在 TARGET_CARD_LIST 放入空陣列 []
TARGET_CARD_LIST: []

# !!! 重要 !!!
# 在 STOP_AT_WONDER_RARE_PACK 放入 true ，遇到能得卡的神包就會停止
STOP_AT_WONDER_RARE_PACK: true

# !!! 重要 !!!
# 在 STOP_AT_NONWONDER_RARE_PACK 放入 true ，遇到不能得卡的神包也會停止
# 要不要開啟，視乎你的需求
# 溫提，販賣帳號違反遊戲條款
STOP_AT_NONWONDER_RARE_PACK: false

# USERNAME: 新帳號的名字
USERNAME: "abc{IDX}"

# LD_EMU_NAME: 模擬器名稱
LD_EMU_NAME: "PTCGP-Gacha-00"

# LDPLAYER_PATH: 雷電模擬器的安裝資料夾，「\」符號要寫成「\\」
LDPLAYER_PATH: "D:\\LDPlayer\\LDPlayer9"
