# 這是單純抽神包的設定檔示範

# LD_EMU_NAME: 模擬器名稱
LD_EMU_NAME: "PTCGP-Gacha-00"

# TARGET_PACK: 抽甚麼包: charizard, mewtwo, pikachu, mew
TARGET_PACK: "mew"

# !!! 重要 !!!
# 在 TARGET_CARD_LIST 放入空陣列 []
TARGET_CARD_LIST: []

# !!! 重要 !!!
# HANDLE_WONDER_RARE_PACK: 處理可得卡神包
HANDLE_WONDER_RARE_PACK: "STOP"

# !!! 重要 !!!
# HANDLE_NONWONDER_RARE_PACK: 處理不可得卡神包
HANDLE_NONWONDER_RARE_PACK: "STOP"

# USERNAME: 新帳號的名字
USERNAME: "abc{IDX}"

# ENABLE_REBOOT: 容許重開模擬器
ENABLE_REBOOT: true
