# 這是單純抽神包的設定檔示範

# TARGET_PACK: 抽甚麼包: charizard, mewtwo, pikachu, mew
TARGET_PACK: "mew"

# !!! 重要 !!!
# 在 TARGET_CARD_LIST 放入空陣列 []
TARGET_CARD_LIST: []

# !!! 重要 !!!
# 在 STOP_AT_RARE_PACK 放入 true 以停止在神包
STOP_AT_RARE_PACK: true

# USERNAME: 新帳號的名字
USERNAME: "abc{IDX}"

# LD_EMU_NAME: 模擬器名稱
LD_EMU_NAME: "PTCGP-Gacha-00"

# LDPLAYER_PATH: 雷電模擬器的安裝資料夾，「\」符號要寫成「\\」
LDPLAYER_PATH: "D:\\LDPlayer\\LDPlayer9"
