# LDPLAYER_PATH: 雷電模擬器的安裝資料夾，「\」符號要寫成「\\」
# 若不設定，則會由系統自動尋找
# LDPLAYER_PATH: "D:\\LDPlayer\\LDPlayer9"

# LD_EMU_NAME: 模擬器名稱
# 請使用英文，中文可能會有問題
LD_EMU_NAME: "PTCGP-Gacha-00"

# TARGET_PACK: 抽甚麼包: charizard, mewtwo, pikachu, mew
TARGET_PACK: "mew"

# TARGET_CARD_LIST: 抽到甚麼卡的時候會停下來，卡片代號請參考 res\card 資料夾
TARGET_CARD_LIST:
  - "cPK_20_000040_00_FUSHIGIBANAex_SR"
  - "cPK_20_000230_00_NASSYex_SR"
  - "cPK_20_000360_00_LIZARDONex_SR"
  - "cPK_20_000410_00_WINDIEex_SR"
  - "cPK_20_000470_00_FIREex_SR"
  - "cPK_20_000560_00_KAMEXex_SR"
  - "cPK_20_000760_00_STARMIEex_SR"
  - "cPK_20_000840_00_FREEZERex_SR"
  - "cPK_20_000960_00_PIKACHUex_SR"
  - "cPK_20_001040_00_THUNDERex_SR"
  - "cPK_20_001230_00_GANGARex_SR"
  - "cPK_20_001290_00_MEWTWOex_SR"
  - "cPK_20_001460_00_KAIRIKYex_SR"
  - "cPK_20_001530_00_GARAGARAex_SR"
  - "cPK_20_001950_00_PUKURINex_SR"
  - "cPK_20_002170_00_CELEBIex_SR"
  - "cPK_20_002320_00_GYARADOSex_SR"
  - "cPK_20_002450_00_MEWex_SR"
  - "cPK_20_002590_00_PTERAex_SR"
  - "cPK_20_002720_00_PIGEOTex_SR"
  - "cTR_20_000110_00_ERIKA_SR"
  - "cTR_20_000120_00_KASUMI_SR"
  - "cTR_20_000130_00_KATSURA_SR"
  - "cTR_20_000140_00_KYOU_SR"
  - "cTR_20_000150_00_SAKAKI_SR"
  - "cTR_20_000160_00_TAKESHI_SR"
  - "cTR_20_000170_00_NATSUME_SR"
  - "cTR_20_000180_00_MATISSE_SR"
  - "cTR_20_000210_00_GREEN_SR"
  - "cTR_20_000220_00_KAKEDASHICHOSAIN_SR"
  - "cTR_20_000230_00_LEAF_SR"
  - "cPK_20_000470_01_FIREex_SAR"
  - "cPK_20_000840_01_FREEZERex_SAR"
  - "cPK_20_001040_01_THUNDERex_SAR"
  - "cPK_20_001230_01_GANGARex_SAR"
  - "cPK_20_001460_01_KAIRIKYex_SAR"
  - "cPK_20_001950_01_PUKURINex_SAR"
  - "cPK_20_002450_01_MEWex_SAR"
  - "cPK_20_002590_01_PTERAex_SAR"

# 以下 HANDLE 開頭的設定，"STOP"=停止, "BACKUP"=備份及繼續刷包, "IGNORE"=忽略
# 若果有 "BACKUP" 選項，ENABLE_REBOOT 必須是 true

# HANDLE_WONDER_TARGET_PACK: 處理可得卡目標包
HANDLE_WONDER_TARGET_PACK: "STOP"

# HANDLE_NONWONDER_TARGET_PACK: 處理不可得卡目標包
HANDLE_NONWONDER_TARGET_PACK: "STOP"

# HANDLE_WONDER_RARE_PACK: 處理可得卡神包
HANDLE_WONDER_RARE_PACK: "STOP"

# HANDLE_NONWONDER_RARE_PACK: 處理不可得卡神包
HANDLE_NONWONDER_RARE_PACK: "STOP"

# HANDLE_WONDER_TARGET_PACK: 處理可得卡目標神包
HANDLE_WONDER_TARGET_RARE_PACK: "STOP"

# HANDLE_NONWONDER_TARGET_PACK: 處理不可得卡目標神包
HANDLE_NONWONDER_TARGET_RARE_PACK: "STOP"

# WONDER_SAINT: 得卡聖人: 如果不是目標包，但同時是可得卡二星包，就不刪帳重刷，增加其他玩家在得卡挑戰中遇到二星包的機會
# 做好事，積功德，抽神包
WONDER_SAINT: true

# MIN_FREE_DISK_SPACE: 硬碟空間不足時停止抽包，單位為位元組 (byte)，預設為 10GB
# 如果所有以上 HANDLE_*_PACK 都是 "STOP" 或 "IGNORE"，則不會檢查
MIN_FREE_DISK_SPACE: 10737418240

# USERNAME: 新帳號的名字
#  {IDX}: 三位數流水號
#  {IDX1}/{IDX2}/{IDX3}/{IDX4}: N位數流水號
#  {YYYY}/{YY}: 4/2位數年份
#  {MM}/{DD}: 2位數月份/日期
#  {hh}/{mm}/{ss}: 2位數小時/分鐘/秒
USERNAME: "abc{IDX}"

# SPEED_FACTOR: 執行速度倍率
SPEED_FACTOR: 1.0

# 刷包動作秒數
# 若不設定，則為 (1/SPEED_FACTOR) 秒
# SWIPE_PACK_SEC: 1.0

# ENABLE_REBOOT: 容許重開模擬器
ENABLE_REBOOT: true
