# DONT CHANGE THIS FILE, PLEASE CHANGE config.yaml

STOP_AT_WONDER_RARE_PACK: true

STOP_AT_NONWONDER_RARE_PACK: false

DEBUG_MODE: true

CHECK_CYCLE_SECONDS: 900 # 15 minutes

# [ZRTRNAFFLV] restart emu to free memory
# if ENABLE_REBOOT set to false, this option will be ignored
FREEMEM_SECONDS: 21600 # 6 hours

INSTANCE_ID: "default"

BACKUP_SEED_ID: "default"

SPEED_FACTOR: 1.0

ENABLE_REBOOT: true
