LDPLAYER_PATH: null

# DONT CHANGE THIS FILE, PLEASE CHANGE config.yaml

HANDLE_WONDER_TARGET_PACK: "STOP"
HANDLE_NONWONDER_TARGET_PACK: "STOP"
HANDLE_WONDER_RARE_PACK: "STOP"
HANDLE_NONWONDER_RARE_PACK: "STOP"
HANDLE_WONDER_TARGET_RARE_PACK: "STOP"
HANDLE_NONWONDER_TARGET_RARE_PACK: "STOP"

WONDER_SAINT: true

# 10GB
MIN_FREE_DISK_SPACE: 10737418240

DEBUG_MODE: true

CHECK_CYCLE_SECONDS: 900 # 15 minutes

# [ZRTRNAFFLV] restart emu to free memory
# if ENABLE_REBOOT set to false, this option will be ignored
FREEMEM_SECONDS: 21600 # 6 hours

INSTANCE_ID: "default"

BACKUP_SEED_ID: "default"

SPEED_FACTOR: 1.0

SWIPE_PACK_SEC: null

ENABLE_REBOOT: true

DEBUG_IMG: false

STATE_DETECT_THRESHOLD: 1

ENABLE_PLATINMODS: false
