LDPLAYER_PATH: null

# DONT CHANGE THIS FILE, PLEASE CHANGE config.yaml

HANDLE_WONDER_TARGET_PACK: "STOP"
HANDLE_NONWONDER_TARGET_PACK: "STOP"
HANDLE_WONDER_RARE_PACK: "STOP"
HANDLE_NONWONDER_RARE_PACK: "STOP"
HANDLE_WONDER_TARGET_RARE_PACK: "STOP"
HANDLE_NONWONDER_TARGET_RARE_PACK: "STOP"

WONDER_SAINT: true

# 10GB
MIN_FREE_DISK_SPACE: 10737418240

DEBUG_MODE: true

CHECK_CYCLE_SECONDS: 900 # 15 minutes

# [ZRTRNAFFLV] restart emu to free memory
# if ENABLE_REBOOT set to false, this option will be ignored
FREEMEM_SECONDS: 21600 # 6 hours

INSTANCE_ID: "default"

BACKUP_SEED_ID: "default"

SWIPE_PACK_SEC: 1.0

SWIPE_UP_SEC: 0.05

ENABLE_REBOOT: true

STATE_DETECT_THRESHOLD: 1

FIRST_SWIPE_UP_KILL_APP: false

ENABLE_PLATINMODS: false

SCREENCAP_METHOD: "WC2501"
