# DONT CHANGE THIS FILE, PLEASE CHANGE config.yaml

STOP_AT_RARE_PACK: true

DEBUG_MODE: true

CHECK_CYCLE_SECONDS: 900 # 15 minutes

# [ZRTRNAFFLV] restart emu to free memory
FREEMEM_SECONDS: 21600 # 6 hours

INSTANCE_ID: "default"
