LDPLAYER_PATH: null

# DONT CHANGE THIS FILE, PLEASE CHANGE config.yaml

HANDLE_WONDER_TARGET_PACK: "STOP"
HANDLE_NONWONDER_TARGET_PACK: "STOP"
HANDLE_WONDER_RARE_PACK: "STOP"
HANDLE_NONWONDER_RARE_PACK: "STOP"
HANDLE_WONDER_TARGET_RARE_PACK: "STOP"
HANDLE_NONWONDER_TARGET_RARE_PACK: "STOP"

WONDER_SAINT: true

# 10GB
MIN_FREE_DISK_SPACE: 10737418240

DEBUG_MODE: true

CHECK_CYCLE_SECONDS: 900 # 15 minutes

# [ZRTRNAFFLV] restart emu to free memory
# if ENABLE_REBOOT set to false, this option will be ignored
FREEMEM_SECONDS: 21600 # 6 hours

INSTANCE_ID: "default"

BACKUP_SEED_ID: "default"

SPEED_FACTOR: 1.0

SWIPE_PACK_SEC: null

ENABLE_REBOOT: true

STATE_DETECT_THRESHOLD: 1

FIRST_SWIPE_UP_KILL_APP: false

ENABLE_PLATINMODS: false

SCREENCAP_METHOD: "WC2501"

# UIWAIT_INFO: 國家地區年齡確認
UIWAIT_INFO_OPEN_YEAR: 4
UIWAIT_INFO_SELECT_YEAR: 9
UIWAIT_INFO_OPEN_MONTH: 4
UIWAIT_INFO_SELECT_MONTH: 9
UIWAIT_INFO_OPEN_REGION: 13
UIWAIT_INFO_SELECT_REGION: 2
UIWAIT_INFO_REGION_OK: 19
UIWAIT_INFO_OK_0: 9
UIWAIT_INFO_OK_1: 15

# UIWAIT_TOC: 使用條款
UIWAIT_TOC_OPEN_TOC: 17
UIWAIT_TOC_CLOSE_TOC: 6
UIWAIT_TOC_AGREE_TOC: 3
UIWAIT_TOC_OPEN_PRIVACY: 17
UIWAIT_TOC_CLOSE_PRIVACY: 6
UIWAIT_TOC_AGREE_PRIVACY: 3
UIWAIT_TOC_OK: 9

# UIWAIT_ACC: 帳號
UIWAIT_ACC_START: 8
UIWAIT_ACC_NO_LINK: 24

# UIWAIT_WELCOME: 歡迎
UIWAIT_WELCOME_DIALOG_0: UIWAIT_COMMON_DIALOG_MID
UIWAIT_WELCOME_DIALOG_1: 6

# UIWAIT_NAME: 名字
UIWAIT_NAME_ICONNAME_INPUTBOX: 7
UIWAIT_NAME_NAME_INPUTBOX: 8
UIWAIT_NAME_NAME_OK: 21
UIWAIT_NAME_ICONNAME_OK_0: 10
UIWAIT_NAME_ICONNAME_OK_1: 27

# UIWAIT_GACHA1: 抽包1
UIWAIT_GACHA1_SELECTPACK: 7
UIWAIT_GACHA1_CONFIRMPACK: 6
UIWAIT_GACHA1_MSG: 32
UIWAIT_GACHA1_NEXT: 11
UIWAIT_GACHA1_END_WHITE: 14

# UIWAIT_MISSION: 任務
UIWAIT_MISSION_SE_BUTTON: 91
UIWAIT_MISSION_MSG_0: 15
UIWAIT_MISSION_CLICK_MISSION: 59
UIWAIT_MISSION_CLICK_COMPLETE: 53
UIWAIT_MISSION_OK: 48

# UIWAIT_GACHA2: 抽包2
UIWAIT_GACHA2_MSG_0: 111
UIWAIT_GACHA2_MSG_1: 16
UIWAIT_GACHA2_CLICK_PACK: 114
UIWAIT_GACHA2_DIALOG: 16

# UIWAIT_WONDER: 得卡挑戰
UIWAIT_WONDER_UNLOCK: 8
UIWAIT_WONDER_CONT: 43
UIWAIT_WONDER_MSG_0: UIWAIT_COMMON_MSG_MID
UIWAIT_WONDER_MSG_1: 12
UIWAIT_WONDER_WONDER_BTN: 70
# 這樣列出了其他玩家或朋友
UIWAIT_WONDER_MSG_2: 24
UIWAIT_WONDER_DIALOG_0: UIWAIT_COMMON_DIALOG_MID
UIWAIT_WONDER_DIALOG_1: UIWAIT_COMMON_DIALOG_MID
UIWAIT_WONDER_DIALOG_2: UIWAIT_COMMON_DIALOG_MID
UIWAIT_WONDER_DIALOG_3: UIWAIT_COMMON_DIALOG_MID
UIWAIT_WONDER_DIALOG_4: 31
# 實際挑戰看看吧
UIWAIT_WONDER_MSG_3: 13
UIWAIT_WONDER_CLICK_WONDERITEM: 32
UIWAIT_WONDER_OK: 9
UIWAIT_WONDER_SHUFFLE_SKIP: 5
UIWAIT_WONDER_CLICK_CARD: 152
UIWAIT_WONDER_CLICK_RESULT1: 116

# UIWAIT_TUTORIALEND:
# 如此一來，基礎的使用教學就結束了
UIWAIT_TUTORIALEND_DIALOG_0: UIWAIT_COMMON_DIALOG_MID
UIWAIT_TUTORIALEND_DIALOG_1: UIWAIT_COMMON_DIALOG_MID
UIWAIT_TUTORIALEND_DIALOG_2: 27
# 開包力恢復到最大值了
UIWAIT_TUTORIALEND_MSG_0: 28
# 那麼
UIWAIT_TUTORIALEND_MSG_1: UIWAIT_COMMON_MSG_MID
# 請好好享受
UIWAIT_TUTORIALEND_MSG_2: 9

# UIWAIT_GACHA5_: 第5抽
# 若開包力用完了
UIWAIT_GACHA5_DIALOG_0: 24
# 請點擊開封1包
UIWAIT_GACHA5_MSG_0: 13
# 開封1包
UIWAIT_GACHA5_BTN_0: 24
# 1個開包沙漏
UIWAIT_GACHA5_MSG_1: 13
# 開包沙漏可透過玩家等級提升
UIWAIT_GACHA5_DIALOG_1: UIWAIT_COMMON_DIALOG_MID
# 購買特級護照
UIWAIT_GACHA5_DIALOG_2: 6
# OK > 白畫面
UIWAIT_GACHA5_BTN_1: 128

# 周回結束, 點擊右下角選單到選單出現
UIWAIT_END_CLICK_MENU: 12
# 周回結束, 選單出現, 點擊其他, 到其他選單出現
UIWAIT_END_CLICK_OTHER: 15
# 周回結束, 其他選單出現, 點擊帳號管理, 到帳號管理選單出現
UIWAIT_END_CLICK_ACCOUNT: 18
# 周回結束, 帳號管理選單出現, 點擊刪除管理資料, 到大刪除儲存資料對話框出現
UIWAIT_END_CLICK_DEL: 9
# 周回結束, 大刪除儲存資料對話框出現, 點擊刪除, 到小刪除儲存資料對話框出現
UIWAIT_END_DIALOG_0: 14

# 主畫面, 點擊包包
UIWAIT_HOME_CLICK_PACK: 100
# 抽包選擇, 選哪種包包
UIWAIT_GACHA_SELECT_PACK: 7
# 抽包選擇, 選了哪種包包, 開封, 白畫面
UIWAIT_GACHA_CONFIRM_PACK: 9
# 抽包畫面, 環形包包選一
UIWAIT_COMMON_GACHA_PACK_RING: 2
# 抽包結果, 首四張卡按了然後下一張出現
UIWAIT_COMMON_GACHA_RESULT_1CARD: 13
# 抽包結果, 最後一張卡
UIWAIT_COMMON_GACHA_RESULT_LASTCARD: 31
# 抽包結果, 五張卡, 點擊繼續, 終身獲得總數, 畫面變白
UIWAIT_COMMON_GACHA_RESULT_5CARD: 82
# 終身獲得總數 16/25 達成, 點擊來繼續, 到向上滑動
UIWAIT_COMMON_TIPS_CLICK: 63
# 卡片收集, 向上滑動, 右下角按鈕, 到卡片清單
UIWAIT_COMMON_SWIPEUP: 32
# 卡片收集, 卡片清單, 右下角按鈕, 畫面變白
UIWAIT_COMMON_CARDLIST: 17

# 串連的對話框, 點擊到下個對話框之間的時間
UIWAIT_COMMON_DIALOG_MID: 13
# 底部小白對話框, 點擊飛字時間
UIWAIT_COMMON_MSG_SKIP: 3
# 底部小白對話框, 點擊到下一個小白對話框的時間
UIWAIT_COMMON_MSG_MID: 3

UIWAIT_OFFSET: 4
